# Generated by Django 4.0.4 on 2022-06-26 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptamberia', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Clientes',
        ),
    ]
