# Generated by Django 4.0.4 on 2022-06-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptamberia', '0002_rename_usuarios_clientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='pedido',
            field=models.CharField(max_length=100),
        ),
    ]
