# Generated by Django 4.0.4 on 2022-06-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptamberia', '0003_alter_pedidos_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='cantidad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
