# Generated by Django 4.0.4 on 2022-06-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptamberia', '0004_pedidos_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='cantidad',
            field=models.CharField(max_length=10),
        ),
    ]
