# Generated by Django 4.0.4 on 2022-06-26 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptamberia', '0006_alter_pedidos_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='cantidad',
            field=models.IntegerField(null=True),
        ),
    ]
